debug: false
input: videos/foreman_cif.y4m
upscale: 444 # used in output_video
output:
  video: outputs/foreman_cif444.y4m # video file name
  # pngs: pngs # path to store pngs
  # y_only: y_only
noise: r # r, g, b, y, u, v, one at a time
params:
  i: 4
  diff_factor: 10