debug: false
input: videos/foreman_cif.y4m
upscale: 444 # used in output_video
output:
  # video: 
  #   path: outputs/foreman_cif444.y4m # video file name
  # pngs: 
  #   path: pngs # path to store pngs
  #   noise: r # r, g, b, y, u, v, one at a time
  y_only: 
    path: y_only
    diff_factor: 10
params:
  i: 2
  