debug: false
input: videos/foreman_cif.yuv
video_params:
  height: 352
  width: 288
  color_space: 420
upscale: 444
writer_no: 2
output_path:
  main_folder: output
  original_folder: original
  reconstructed_folder: reconstructed
  residual_folder: residual
  mv_folder: mv
  meta_file: meta
  mae_file: mae.txt
  uv_folder: uv
params:
  i: 8 # 2, 8, 64
  r: 2 # 1, 4, 8
  stop_at: 10 # stop after processing how many frames, -1 to disable
  qp: 3
  i_period: 4

statistics:
  path: statistics

decoder:
  input_path:
    mv_folder: output/mv
    residual_folder: output/residual
    meta_file: output/meta
  output_path:
    main_folder: decoder_output
