debug: false
input: videos/foreman_cif.yuv
video_params:
  height: 288
  width: 352
  color_space: 420
upscale: 444
output_path:
  main_folder: output
  original_folder: original
  reconstructed_folder: reconstructed
  residual_folder: residual
  mv_folder: mv
  meta_file: meta
  mae_file: mae.txt
  uv_folder: uv
  split_counter_file: split_counter.txt
params:
  i: 16
  r: 4 # 1, 4, 8
  stop_at: 10 # stop after processing how many frames, -1 to disable
  qp: 1
  i_period: 8
  nRefFrames: 2 # 1, 2, 3, 4
  VBSEnable: true # true, false
  FMEEnable: true # true, false
  FastME: true # true, false

statistics:
  path: statistics

decoder:
  input_path:
    mv_folder: output/mv
    residual_folder: output/residual
    meta_file: output/meta
  output_path:
    main_folder: decoder_output
