debug: false
input: videos/foreman_cif.y4m
upscale: 444 # used in output_video
output_path:
  main_folder: output
  original_folder: original
  reconstructed_folder: reconstructed
  residual_folder: residual
  mv_folder: mv
  done_file: done
  mae_file: mae.txt
  uv_folder: uv
params:
  i: 2 # 2, 8, 64
  r: 1 # 1, 4, 8
  n: 1 # 1, 2, 3
  diff_factor: 10

statistics:
  path: data