debug: false
input: videos/foreman_cif.y4m
upscale: 444 # used in output_video
# output_video: outputs/foreman_cif444.y4m # video file name
output_pngs: pngs # path to store pngs
noise: r # r, g, b, y, u, v, one at a time