debug: false
input: videos/foreman_cif.y4m
upscale: 444 # used in output_video
output_path:
  main_folder: output
  original_folder: original
  reconstructed_folder: reconstructed
  residual_folder: residual
  mv_folder: mv
  meta_file: meta
  mae_file: mae.txt
  uv_folder: uv
params:
  i: 8 # 2, 8, 64
  r: 4 # 1, 4, 8
  n: 3 # 1, 2, 3

statistics:
  path: statistics

decoder:
  input_path:
    mv_folder: output/mv
    residual_folder: output/residual
    meta_file: output/meta
  output_path:
    main_folder: decoder_output