debug: false
input: videos/ducks_take_off_420_720p50.yuv
video_params:
  height: 720
  width: 1280
  fps: 50
  color_space: 420
upscale: 444
output_path:
  main_folder: output
  original_folder: original
  reconstructed_folder: reconstructed
  residual_folder: residual
  mv_folder: mv
  meta_file: meta
  mae_file: mae.txt
  uv_folder: uv
  split_counter_file: split_counter.txt
params:
  i: 16
  r: 16
  stop_at: -1 # stop after processing how many frames, -1 to disable
  qp: 3
  i_period: 10
  nRefFrames: 1 # 1, 2, 3, 4
  VBSEnable: true # true, false
  FMEEnable: true # true, false
  FastME: true # true, false
  RCflag: 0 # 0 -> OFF, 1 -> ON, 2, 3
  targetBR: 2.4 mbps # <x> bps, <x> kbps, <x> mbps
  ParallelMode: 2 # 0, 1, 2, 3

statistics:
  path: statistics

decoder:
  input_path:
    mv_folder: output/mv
    residual_folder: output/residual
    meta_file: output/meta
  output_path:
    main_folder: decoder_output
